name: ci

on:
  workflow_dispatch:

env:
  TF_IN_AUTOMATION: 1

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    runs-on: ubuntu-20.04
    environment: prod
    steps:
    - name: Azure login
      uses: azure/login@v1
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        allow-no-subscriptions: true

    - name: Terraform plan composite action
      uses: ./.github/actions/tf-common-plan.yml
      with:
        tf-root-dir: ${{ github.workspace }}
        tf-version: ~1.2.0
